version: '2.4'
services:
  bot:
    build:
      context: .
    restart: always
    env_file:
      - ./.env
    network_mode: 'host'

  lavalink:
    build:
      context: .
      dockerfile: Dockerfile-Lavalink
    restart: always
    env_file:
      - ./.env_lavalink
    ports:
      - 7000:7000
    mem_limit: 4GB

  redis:
    image: "redis:4-alpine"
    restart: always
    ports:
      - 6379:6379
    mem_limit: 1GB
