on: pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: iCrawl/eslint-action-marine@master
      env:
        FOLDERS: src
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
